# Generated by Django 4.2.3 on 2023-07-20 09:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Indie', 'Indie'), ('Platformer', 'Platformer'), ('RPG', 'RPG'), ('Strategy', 'Strategy'), ('Shooter', 'Shooter'), ('Sports', 'Sports'), ('Racing', 'Racing')], default=None, max_length=20, null=True)),
                ('score', models.IntegerField(default=0)),
                ('num_ratings', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_rating', models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_rating', to='game_recomm.game')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('game', 'user')},
            },
        ),
    ]
